// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/approval/[approvalGroupId].tsx";
import * as $4 from "./routes/approval/[approvalGroupId]/[approvalState].tsx";
import * as $5 from "./routes/approval/_middleware.tsx";
import * as $6 from "./routes/auth/code.tsx";
import * as $7 from "./routes/auth/login.tsx";
import * as $8 from "./routes/auth/logout.tsx";
import * as $9 from "./routes/deployment/[deploymentId].tsx";
import * as $10 from "./routes/deployment/_middleware.tsx";
import * as $11 from "./routes/index.tsx";
import * as $$0 from "./islands/Auth.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/approval/[approvalGroupId].tsx": $3,
    "./routes/approval/[approvalGroupId]/[approvalState].tsx": $4,
    "./routes/approval/_middleware.tsx": $5,
    "./routes/auth/code.tsx": $6,
    "./routes/auth/login.tsx": $7,
    "./routes/auth/logout.tsx": $8,
    "./routes/deployment/[deploymentId].tsx": $9,
    "./routes/deployment/_middleware.tsx": $10,
    "./routes/index.tsx": $11,
  },
  islands: {
    "./islands/Auth.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
