// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/approval/[approvalGroupId].tsx";
import * as $3 from "./routes/auth/code.tsx";
import * as $4 from "./routes/auth/login.tsx";
import * as $5 from "./routes/auth/logout.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LogIn.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/approval/[approvalGroupId].tsx": $2,
    "./routes/auth/code.tsx": $3,
    "./routes/auth/login.tsx": $4,
    "./routes/auth/logout.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LogIn.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
