// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/approval/[approvalGroupId].tsx";
import * as $5 from "./routes/approval/[approvalGroupId]/[approvalState].tsx";
import * as $6 from "./routes/approval/_middleware.tsx";
import * as $7 from "./routes/approvals/_middleware.tsx";
import * as $8 from "./routes/approvals/index.tsx";
import * as $9 from "./routes/auth/code.tsx";
import * as $10 from "./routes/auth/login.tsx";
import * as $11 from "./routes/auth/logout.tsx";
import * as $12 from "./routes/deployment/[deploymentId].tsx";
import * as $13 from "./routes/deployment/_middleware.tsx";
import * as $14 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/about.tsx": $3,
    "./routes/approval/[approvalGroupId].tsx": $4,
    "./routes/approval/[approvalGroupId]/[approvalState].tsx": $5,
    "./routes/approval/_middleware.tsx": $6,
    "./routes/approvals/_middleware.tsx": $7,
    "./routes/approvals/index.tsx": $8,
    "./routes/auth/code.tsx": $9,
    "./routes/auth/login.tsx": $10,
    "./routes/auth/logout.tsx": $11,
    "./routes/deployment/[deploymentId].tsx": $12,
    "./routes/deployment/_middleware.tsx": $13,
    "./routes/index.tsx": $14,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
